//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Налоговая.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT
    {
        public int id_act { get; set; }
        public int id_type { get; set; }
        public int id_termsOfUse { get; set; }
        public int id_taxAuthority { get; set; }
        public int id_conclusion { get; set; }
        public int id_equipments { get; set; }
        public int id_users { get; set; }
        public string name { get; set; }
        public string manufacturer { get; set; }
        public string condition { get; set; }
        public short year_of_issue { get; set; }
        public System.DateTime commissioning { get; set; }
        public string equipment_number { get; set; }
        public string assessment { get; set; }
        public System.DateTime date { get; set; }
        public string application { get; set; }
    
        public virtual conclusion conclusion { get; set; }
        public virtual equipments equipments { get; set; }
        public virtual taxAuthority taxAuthority { get; set; }
        public virtual termsOfUse termsOfUse { get; set; }
        public virtual type type { get; set; }
        public virtual users users { get; set; }
    }
}
